apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.commonVolume.name }}
spec:
  storageClassName: standard
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi